# Generated by Django 5.1.3 on 2024-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('categoria', models.IntegerField(choices=[(1, 'T Shirts'), (2, 'Shorts'), (3, 'Pants'), (4, 'Hoodies'), (5, 'Shirts'), (6, 'Accessories')], default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
