# Generated by Django 5.1.3 on 2024-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'T Shirts'), (2, 'Shorts'), (3, 'Pants'), (4, 'Hoodies'), (5, 'Accessories')], default=1),
        ),
    ]
